services:
  app:
    container_name: poe2-rag-app
    build:
      context: .
      args:
        - EMBEDDING_MODEL
    ports:
      - "8003:8000"
    restart: always
    depends_on:
      qdrant:
        condition: service_healthy
    env_file:
      - .env
    environment:
      QDRANT_URL: http://qdrant:6333
  qdrant:
    image: qdrant/qdrant:latest
    container_name: poe2-rag-qdrant
    ports:
      - "${QDRANT_HOST_PORT:-6333}:6333"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/6333'"]
      interval: 5s
      retries: 5
    volumes:
      - qdrant_storage:/qdrant/storage
volumes:
  qdrant_storage:
